JK BMS V1.3 Support / SOC Calculations based on Min/Max Cell Voltage
shining-man/bsc_fw pull request #49
Opened 2023-08-02 17:57 UTC by drakesoft

JK BMS V1.3 Protocol RS485 Support for JK-B1A24S  / JK-B2A24S Balancer
 SOC Calculations based on Min/Max Cell Voltage

2023-08-07 06:49 UTC, shining-man requested changes
I have looked at the changes and commented in two places.

2023-08-07 06:49 UTC, shining-man commented on include/defines.h
The parameters ID_PARAM_TEMP_ALARM_TEMP_QUELLE and ID_PARAM_TEMP_ALARM_BMS_QUELLE originally had the IDs 128 and 129. If existing IDs are changed, the settings are incorrect at the user. Therefore, please do not change any IDs. 
The new parameter ID_PARAM_BMS_BALUE_ADJUSTMENTS_SOC0_CELL_VOLTAGE should therefore have the ID 130.

In addition, the parameter ID_PARAM_BMS_BALUE_ADJUSTMENTS_SOC0_CELL_VOLTAGE is duplicated.

Maybe the problem was caused by my last commit.

2023-08-07 06:49 UTC, shining-man commented on platformio.ini
Please leave the platformio.ini in its original state and do not replace it with your own board.

2023-08-09 20:28 UTC, drakesoft commented
I fixed the issues you mentioned.

2023-08-19 19:00 UTC, shining-man commented
Can you possibly add the BMS to the table in BmsData.h? There you can see which data the BMS delivers.

I have seen that you do not fill the bmsErrors and bmsStateFETs or not correctly. This means that the BMS can only be used correctly for monitoring. I will therefore add a comment that the BMS can only be used for monitoring. 
If the BMS is also to be used for charge control, etc., it also needs all the necessary data (bmsErrors, bmsStateFETs, ...).

2023-08-29 22:12 UTC, merged